"""Messages and everything hanging off them: receipts, reactions, attachments.

Design notes
------------
* ``messages.id`` is a monotonically increasing integer, so it doubles as the
  cursor for pagination *and* as the ordering key. No ``created_at`` sorting.
* ``client_id`` is a UUID generated by the sending browser. Together with the
  unique constraint ``(sender_id, client_id)`` it makes sending idempotent: if a
  client retries after a dropped socket, the server returns the existing row
  instead of duplicating the message. This is what makes the optimistic UI safe.
* Receipts are one row *per recipient per message*. That gives us per-user
  delivered/read timestamps, which is exactly what group "lowest common status"
  needs, and it is cheaper to query than JSON columns.
* Deletes are tombstones (``deleted_at``) so other clients can react to the
  event; disappearing messages are hard-deleted by the sweeper.
"""

from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base, utcnow


class Message(Base):
    __tablename__ = "messages"
    __table_args__ = (
        CheckConstraint("kind IN ('text', 'attachment', 'system')", name="ck_messages_kind"),
        # Idempotent send: a client retry can never insert the same message twice.
        UniqueConstraint("sender_id", "client_id", name="uq_messages_sender_client"),
        # History pagination: newest-first slice of one conversation.
        Index("ix_messages_conversation_id_id", "conversation_id", "id"),
        # Disappearing-message sweeper.
        Index("ix_messages_expires_at", "expires_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    conversation_id: Mapped[int] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False
    )
    # NULL sender == system message ("Meera added Aarav", "timer changed", ...)
    sender_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))

    client_id: Mapped[str | None] = mapped_column(String(64))

    kind: Mapped[str] = mapped_column(String(12), default="text", nullable=False)
    body: Mapped[str | None] = mapped_column(Text)

    reply_to_id: Mapped[int | None] = mapped_column(ForeignKey("messages.id", ondelete="SET NULL"))
    system_event: Mapped[str | None] = mapped_column(String(40))
    # Machine-readable detail for system messages (actor, targets, value) so
    # the client can render "You added Meera" instead of parsing English text.
    system_payload: Mapped[str | None] = mapped_column(Text)

    expires_at: Mapped[datetime | None] = mapped_column(DateTime)
    edited_at: Mapped[datetime | None] = mapped_column(DateTime)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)

    sender: Mapped["User | None"] = relationship()  # noqa: F821

    receipts: Mapped[list["MessageReceipt"]] = relationship(
        back_populates="message", cascade="all, delete-orphan"
    )
    # "selectin" = one extra query per page instead of one per row (no N+1).
    reactions: Mapped[list["Reaction"]] = relationship(
        back_populates="message", cascade="all, delete-orphan", lazy="selectin"
    )
    attachments: Mapped[list["Attachment"]] = relationship(
        back_populates="message", cascade="all, delete-orphan", lazy="selectin"
    )
    reply_to: Mapped["Message | None"] = relationship(remote_side=[id], foreign_keys=[reply_to_id])


class MessageReceipt(Base):
    """Delivery / read state of one message for one recipient."""

    __tablename__ = "message_receipts"
    __table_args__ = (
        Index("ix_receipts_user_read_at", "user_id", "read_at"),
        Index("ix_receipts_message", "message_id"),
    )

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime)
    read_at: Mapped[datetime | None] = mapped_column(DateTime)

    message: Mapped[Message] = relationship(back_populates="receipts")


class Reaction(Base):
    """One emoji per user per message (Signal's behaviour)."""

    __tablename__ = "reactions"

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    emoji: Mapped[str] = mapped_column(String(8), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)

    message: Mapped[Message] = relationship(back_populates="reactions")


class Attachment(Base):
    """Files stored on disk; only metadata lives in the database."""

    __tablename__ = "attachments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), index=True, nullable=False
    )
    file_name: Mapped[str] = mapped_column(String(255), nullable=False)
    mime_type: Mapped[str] = mapped_column(String(120), nullable=False)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    storage_path: Mapped[str] = mapped_column(String(255), nullable=False)
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)

    message: Mapped[Message] = relationship(back_populates="attachments")


class MessageDeletion(Base):
    """Delete-for-me: hides one message from one user only.

    A join table (message_id, user_id) is the tidy way to model "this message is
    gone for me but still visible to everybody else" - no flags on the message,
    no data loss for other participants.
    """

    __tablename__ = "message_deletions"

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    deleted_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
